Update 10-matrices.yaml

diff --git a/.github/workflows/10-matrices.yaml b/.github/workflows/10-matrices.yaml
--- a/.github/workflows/10-matrices.yaml
+++ b/.github/workflows/10-matrices.yaml
@@ -7,29 +7,19 @@ jobs:
   backwards-compatibility:
     runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
-        node-version: [16.x, 18.x, 20.x, 21.x]
-        os: [ubuntu-latest, windows-latest]
-        tag: [default, experimental]
-        exclude:
-          - node-version: 21.x
-            os: windows-latest
-          - node-version: 16.x
-            os: windows-latest
-          - node-version: 16.x
-            tag: experimental
-          - node-version: 18.x
-            tag: experimental
-          - node-version: 20.x
-            tag: experimental
-          - node-version: 21.x
-            os: ubuntu-latest
-            tag: default
-          - node-version: 21.x
-            os: windows-latest
-            tag: default
-          
+        node-version: [18.x, 20.x]
+        os:
+          - ubuntu-latest
+          - windows-latest
+        include:
+          - os: ubuntu-latest
+            node-version: 21.x
+            tag: experimental  # Assuming we want to add a tag for this combination
+          - os: ubuntu-latest
+            tag: linux         # Additional tag for ubuntu-latest
+
     name: ${{ matrix.os }}-node-${{ matrix.node-version }}-tag-${{ matrix.tag }}
 
     steps:
@@ -40,7 +30,7 @@ jobs:
 
     - name: Fail if experimental
       if: ${{ matrix.tag == 'experimental' }}
-      run: exit 1
+      run: exit 1  # Exits with a failure code for experimental jobs
 
     - name: Perform some tests
       run: |
